### ISSUE TITLE
port 8080 is allocated , another port can be set for novnc ?

### ISSUE THREAD

**Issue by bugbounted** [Filadeus/windows10-in-docker#2]
Hi [Filadeus](https://github.com/Filadeus),
my vps port 8080 is allocated , another port can be set for novnc ?
please if it's possible help me to run this project on ubuntu 22.04 server edition (No GUI) vps & browse it on my pc browser using server ip.
waiting for your hints
finest regards

**Comment by bugbounted** [comment]
after stop current project docker-composeyml & start this project docker-compose.yml & browse port 8080 of my vps just see directory files like below :

Directory listing for /
[app/](http://1.1.1.1:8080/app/)
[core/](http://1.1.1.1:8080/core/)
[include/](http://1.1.1.1:8080/include/)
[utils/](http://1.1.1.1:8080/utils/)
[vendor/](http://1.1.1.1:8080/vendor/)
[vnc.html](http://1.1.1.1:8080/vnc.html)
[vnc_auto.html@](http://1.1.1.1:8080/vnc_auto.html)
[vnc_lite.html](http://1.1.1.1:8080/vnc_lite.html)

please help me

**Comment by Filadeus** [comment]
Hi! 
When using docker-compose.yml to start up container stack, you can edit ports or resolution in the appropriate fields. E.g. you can change port 8080 on host to whatever you want, it should look something like this:
```
    ports:
      - "5025:8080"
```
Actual noVNC interface is located at **http://ip.address/vnc.html**
