### ISSUE TITLE
failed: Connection timed out to https://git.efimio.ru/efim/windows10-in-docker/raw/branch/master/isoCheck.ps1

### ISSUE THREAD

**Issue by bugbounted** [Filadeus/windows10-in-docker#3]
Starting windows10-in-docker_novnc_1 ... done
Starting windows10-in-docker_win10_1 ... done
Attaching to windows10-in-docker_novnc_1, windows10-in-docker_win10_1
win10_1  | --2022-06-28 07:13:31--  https://git.efimio.ru/efim/windows10-in-docker/raw/branch/master/isoCheck.ps1
novnc_1  | + RUN_FLUXBOX=no
novnc_1  | + RUN_XTERM=no
novnc_1  | + case $RUN_FLUXBOX in
novnc_1  | + rm -f /app/conf.d/fluxbox.conf
novnc_1  | + case $RUN_XTERM in
novnc_1  | + rm -f /app/conf.d/xterm.conf
novnc_1  | + exec supervisord -c /app/supervisord.conf
novnc_1  | 2022-06-28 07:13:31,381 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
novnc_1  | 2022-06-28 07:13:31,381 INFO Included extra file "/app/conf.d/websockify.conf" during parsing
novnc_1  | 2022-06-28 07:13:31,381 INFO Included extra file "/app/conf.d/x11vnc.conf" during parsing
novnc_1  | 2022-06-28 07:13:31,381 INFO Included extra file "/app/conf.d/xvfb.conf" during parsing
novnc_1  | 2022-06-28 07:13:31,384 INFO supervisord started with pid 1
win10_1  | Resolving git.efimio.ru (git.efimio.ru)... 151.0.14.124
novnc_1  | 2022-06-28 07:13:32,387 INFO spawned: 'websockify' with pid 11
novnc_1  | 2022-06-28 07:13:32,388 INFO spawned: 'xvfb' with pid 12
novnc_1  | 2022-06-28 07:13:32,390 INFO spawned: 'x11vnc' with pid 13
novnc_1  | 2022-06-28 07:13:33,400 INFO success: websockify entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
novnc_1  | 2022-06-28 07:13:33,400 INFO success: xvfb entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
novnc_1  | 2022-06-28 07:13:33,400 INFO success: x11vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
win10_1  | Connecting to git.efimio.ru (git.efimio.ru)|151.0.14.124|:443... failed: Connection timed out.
win10_1  | Retrying.
win10_1  |
win10_1  | --2022-06-28 07:15:42--  (try: 2)  https://git.efimio.ru/efim/windows10-in-docker/raw/branch/master/isoCheck.ps1

**Comment by bugbounted** [comment]
also in docker-compose.yml line 5 link git.efimio.ru/efim/windows10-in-docker:latest is on 404 page !!

**Comment by Filadeus** [comment]
So sorry for the inconvenience. Issue is resolved now.
